### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by SergioML9** [wallix/triplestore#4]
Hi,

I'd like to know if there is any way to decode prefixes. When I try to decode a file containing triples after prefixes definition I get the following error:

`lenient parsing: line 1: invalid subject in @prefix owl: <http://www.w3.org/2002/07/owl#> .`

Thanks in advance !

**Comment by simcap** [comment]
@SergioML9 it seems you are referring to prefixes from the Turtle RDF format. 

At this point, the triplestore only supports the format `NTriple` (and a custom binary format). It does not supports the Turtle format.

**Comment by SergioML9** [comment]
Yes, I was referring to Turtle RDF format. Ok, thanks for your clarification !
