### ISSUE TITLE
Adding JSON serialisation and exporting methods

### ISSUE THREAD

**Issue by mattrayner** [wallix/triplestore#5]
Hi, I'm using triplestore as part of another project which Marshalls triple objects out to JSON.

At the moment I'm having to duplicate some of the code from within triplestore in order to Marshall triples as part of my response. Would you be open to a PR which added JSON serialisation and exported some of the internal types for use outside of triplestore?

Thanks for a great project,
Matt

**Comment by simcap** [comment]
@mattrayner If I understand correctly you want to export/marshal internal objects towards JSON. If it is regular JSON obviously you will lose information, so I am guessing you are thinking of the JSON format that can represents linked data which is JSON-LD?

And indeed `triplestore` should supports JSON-LD. I left the company that supported the project so I will not have the admin rights on the repo (hopefully someone else has it).

But a PR is always open, but I guess it would have to be towards a format that do not loose linked data information.

**Comment by simcap** [comment]
@mattrayner ... and thanks for using the project!

**Comment by mattrayner** [comment]
@simcap yes and no for the JSON-LD, my use for your package is as part of a native extension within a ruby gem for @ukparliament - we're moving some CPU intensive tasks away from ruby and into a GO extension.

We provide multiple data views which expose n-triple, turtle, rdfxml, json-ld etc through content negotiation and extensions i.e. https://beta.parliament.uk/people/43RHonMf.jsonld

Instead, our use is for grouping statements by subject and edges by statement and predicate so that within our Ruby environment we can create linked object representations.

In my main use case I'm creating this map (excuse the work in progress): https://github.com/ukparliament/gromnative/blob/master/ext/gromnative.go#L13

Although my use case isn't JSON-LD directly, work on adding serialisation and exporting throughout would benefit my use

**Comment by simcap** [comment]
Ok, not sure I get everything, but it seems that what you want to do is to indexed efficiently some triples in a data structure more than having a new/specific marshaling.  

My thought is that one cannot really add to the `triplestore` library a custom/specific way of marshaling.

Also it seems you can do everything you want to do by using the triple objects exposed by the library. But maybe you are efficiency/performance conscious and want "your transformation" to happen within the library.

**Comment by mattrayner** [comment]
I'm closing this off as no longer relevant :)
